'use client'


// 02 EXTERNAL

// 03 REACT / NODE / NEXTJS
import { useEffect, useState } from "react"

// 05 SUPERMANIFOLD COMPONENTS
import HeaderA from '@/components/global/HeaderA';
import FooterA from '@/components/global/FooterA';

// 07 SUPERMANIFOLD FUNCTIONS
import useScrollProgress from '@/lib/useScrollProgress';

// 11 SUPERMANIFOLD STYLES
import '@/styles/main.scss'



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  const [progressFactor, setProgressFactor] = useState(0)
  // const progress = useScrollProgress()
  
  // console.log(progress)
  // let progressFactor = .98
  function remap(value: number, fromLow: number, fromHigh: number, toLow: number, toHigh: number): number {
    const normalizedValue = (value - fromLow) / (fromHigh - fromLow);
    const remappedValue = normalizedValue * (toHigh - toLow) + toLow;
    return Math.max(Math.min(remappedValue, Math.max(toLow, toHigh)), Math.min(toLow, toHigh));
  }
  
  function remap01(value: number, toLow: number, toHigh: number): number {
    const remappedValue = value * (toHigh - toLow) + toLow;
    return Math.max(Math.min(remappedValue, Math.max(toLow, toHigh)), Math.min(toLow, toHigh));
  }


  useEffect(() => {

    const handleScroll = () => {
      // this is the footer spacer height
      const footerMaskHeight = window.innerHeight * .8;
      // this is the starting position of the factor
      let start = document.body.scrollHeight - (window.innerHeight + footerMaskHeight)
      start = Math.max(start, 0)
      // this is the ending position of the factor
      const end = document.body.scrollHeight - (window.innerHeight)

      const normalizedProgress = remap(window.scrollY, start, end, 0, 1)
      // console.log(normalizedProgress)
      setProgressFactor(normalizedProgress)
    }

    window.addEventListener('scroll', handleScroll)

    return () => {
      window.removeEventListener('scroll', handleScroll)
    }
  }, [])


  return (
    <html lang="en" >
      <body>

      <HeaderA />

      <div
        style={{
          backgroundColor: 'white',
          transformOrigin: 'bottom center',
          transform:
          `translate3d(0px, 0px, 0px) 
          scale3d(${remap01(progressFactor, 1, .98)}, ${remap01(progressFactor, 1, .98)}, 1) 
          rotateX(0deg) 
          rotateY(0deg) 
          rotateZ(0deg) 
          skew(0deg)`,
          transformStyle: 'preserve-3d',
          borderRadius: '0 0 24px 24px',
        }}>
          {children}
        </div>


      <FooterA opacity={remap01(progressFactor, 0, 1)}/>
      </body>

    </html>
  );
}







// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }


// import localFont from 'next/font/local'
// const nmtl = localFont({
//   src: [
//     // {
//     //   path: '../../public/fonts/PPNeueMontreal-Thin.otf',
//     //   weight: '100'
//     // },
//     {
//       path: '../../public/fonts/PPNeueMontreal-Book.otf',
//       weight: '400'
//     },
//     // {
//     //   path: '../../public/fonts/PPNeueMontreal-Medium.otf',
//     //   weight: '500'
//     // },
//   ],
//   variable: '--nmtl'
// })



